spring:
  datasource:

    # PostgresのIPアドレス/ポート番号/DB名
    url: jdbc:postgresql://localhost:5432/postgres

    # Postgresのユーザ名
    username: postgres

    # Postgresのパスワード
    password: postgres

    # PostgresのJDBCドライバ
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:

      # @Entityに対応するテーブルが無ければ作成
      ddl-auto: create-drop

recaptcha:
  validation:
    secret-key: 6LdpQrYZAAAAAOkbIdNvcWb40nVyPYmtPnbv-uU9

firebase:
  databaseURL: https://tk-income-360cd.firebaseio.com
  serviceAccount: C:\Users\tk_23\firebase\firebaseServiceAccountKey.json

logging:
  level:
    root: INFO
    org.springframework: INFO

app:
  allowedOrigin: http://localhost:8081
